# Production values for ejabberd
# These values override the defaults in ejabberd/values.yaml for production

replicaCount: 3

image:
  pullPolicy: Always

service:
  type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ejabberd.yourdomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ejabberd-tls
      hosts:
        - ejabberd.yourdomain.com

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ejabberd:
  domain: "yourdomain.com"
  admin:
    user: "admin"
    password: "{{ .Values.ejabberd.admin.passwordSecret }}"  # Use a secret in production
  database:
    type: "postgresql"  # Use external database in production
    # Configure your database connection here 