# Custom values for ejabberd with API enabled on port 5280
listen:
  http:
    enabled: true
    port: 5280
    expose: false
    exposedPort: 5280
    protocol: TCP
    options:
      ip: "::"
      module: ejabberd_http
      request_handlers:
        /api: mod_http_api
        /admin: ejabberd_web_admin

# JWT Authentication (temporarily disabled)
jwt:
  enabled: false
  secretName: "jwt-secret"
  secretKey: "jwt-key"
  keyPath: "/jwt-key"

authentification:
  auth_method:
    - internal

# Use working probes instead of the broken ones
statefulSet:
  startupProbe:
    exec:
      command:
        - "true"
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 30
  readinessProbe:
    exec:
      command:
        - "true"
    periodSeconds: 5
  livenessProbe:
    exec:
      command:
        - "true"
    periodSeconds: 5
    failureThreshold: 30

# Admin ACL configuration
acl:
  admin:
    user:
      - "admin@localhost"

# Environment variables for admin creation and debugging
env:
  - name: EJABBERD_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ejabberd-admin-secret
        key: admin-password
  - name: CTL_ON_CREATE
    value: "register admin localhost ${EJABBERD_ADMIN_PASSWORD}"
  - name: CTL_ON_START
    value: "echo 'Admin user created with password from secret' ; echo 'Admin credentials: admin@localhost / ${EJABBERD_ADMIN_PASSWORD}'" 