# Custom values for ejabberd with API enabled on port 5280
listen:
  http:
    enabled: true
    port: 5280
    expose: false
    exposedPort: 5280
    protocol: TCP
    options:
      ip: "::"
      module: ejabberd_http
      request_handlers:
        /api: mod_http_api
        /admin: ejabberd_web_admin

# JWT Authentication
jwt:
  enabled: true
  secretName: "jwt-secret"
  secretKey: "jwt-key"
  jidField: "sub"
  keyPath: "/opt/ejabberd/jwt-key"

# Authentication method
authentification:
  auth_method:
    - jwt
    - mnesia 