# ejabberd configuration file
# This file contains the ejabberd server configuration
# Reference: https://docs.ejabberd.im/admin/configuration/

# Define your XMPP domains
hosts:
  - "ejabberd.local"

# Logging level
loglevel: info

# Listen configuration
listen:
  # XMPP client connections
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
  # XMPP server-to-server connections
  -
    port: 5269
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  # HTTP admin interface
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/admin": ejabberd_web_admin
      "/api": mod_http_api

# Authentication method
auth_method: internal

# Module configuration
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_disco: {}
  mod_http_api: {}
  mod_last: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_time: {}
  mod_vcard: {}
  mod_version: {}

# Access rules
access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  trusted_network:
    - allow

# Shaper rules
shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

# Shapers
shaper:
  normal: 1000
  fast: 50000 