apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ejabberd.fullname" . }}-config
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
data:
  ejabberd.yml: |
{{ .Files.Get .Values.ejabberd.configFile | nindent 4 }} 