{{- if (not .Values.listen) }}
{{- fail "You need to define at least one listener in .Values.listen" -}}
{{- else if (not .Values.certFiles.secretName) }}
{{- fail "You need to define your TLS cert secretName in .Values.certFiles.secretName" -}}
{{- end }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ejabberd.fullname" . }}
  namespace: {{ template "ejabberd.namespace" . }}
  labels:
  {{- include "ejabberd.labels" . | nindent 4 }}
  {{- with .Values.statefulSet.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.statefulSet.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.headless }}
  serviceName: {{ include "ejabberd.fullname" . }}-headless
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 1 .Values.statefulSet.replicas }}
  {{- end }}
  {{- if .Values.statefulSet.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.statefulSet.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ejabberd.selectorLabels" . | nindent 6 }}
  updateStrategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  minReadySeconds: {{ .Values.statefulSet.minReadySeconds }}
  template: {{ template "ejabberd.podTemplate" . }}
  {{- if and (not .Values.persistence.existingClaim) .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mnesia
        annotations:
        {{- range $key, $value := .Values.persistence.annotations }}
          {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      {{- else if (not .Values.persistence.enabled) }}
        - name: mnesia
          emptyDir: {}
  {{- end }}
