apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ejabberd.fullname" . }}-secret
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT secret for Firebase token validation
  jwt_secret: {{ .Values.ejabberd.auth.methods.jwt.key | b64enc | quote }}
  
  # Admin password (for internal auth fallback)
  admin_password: {{ "admin123" | b64enc | quote }}
  
  # Database passwords (if using external database)
  {{- if eq .Values.ejabberd.database.type "sql" }}
  db_password: {{ .Values.ejabberd.database.sql.password | b64enc | quote }}
  {{- end }}
  
  # LDAP password (if using LDAP auth)
  {{- if .Values.ejabberd.auth.methods.ldap.enabled }}
  ldap_password: {{ .Values.ejabberd.auth.methods.ldap.bind_password | b64enc | quote }}
  {{- end }}
---
{{- if .Values.ejabberd.tls.custom_cert.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ejabberd.fullname" . }}-tls
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ejabberd.tls.custom_cert.cert | b64enc | quote }}
  tls.key: {{ .Values.ejabberd.tls.custom_cert.key | b64enc | quote }}
{{- end }} 